Feature sys scene interactive
as-demo-1/song_of_soul pull request #49
Opened 2022-01-15 09:19 UTC by ringo199

场景交互分支合并，改动了playerController的部分，并解决了playerController以及itemso部分的冲突

2022-01-15 13:09 UTC, IsaacJade commented on Silksong/Assets/Scripts/Dialogue/TalkController.cs
> +                NPCText.text = TalkManager.Instance.TalkContent[_id];
这部分一直在重复调用，可以写个function简化一下

2022-01-15 13:10 UTC, IsaacJade commented on Silksong/Assets/Scripts/Dialogue/TalkController.cs
> +                        NPCName.text = TalkManager.Instance.TalkNPC[_id];
同上

2022-01-15 13:11 UTC, IsaacJade commented on Silksong/Assets/Scripts/Dialogue/TalkController.cs
> +            _id = TalkManager.Instance.TalkNo[_id];//_id等于Next_id
同上

2022-01-15 13:14 UTC, IsaacJade commented on Silksong/Assets/Scripts/Dialogue/TalkManager.cs
> +    public Dictionary<int, string> TalkNPC = new Dictionary<int, string>();//int是对话ID，string是说话的NPC名字
npc索引可以考虑用guid，方便日后搜索

2022-01-15 13:46 UTC, IsaacJade requested changes

2022-01-15 13:46 UTC, IsaacJade commented on Silksong/Assets/Scripts/Dialogue/TalkManager.cs
> +public class TalkManager
直接继承mono吧，talkSO manager 单独出来也看不到这些配置，也没必要单开一个

2022-01-15 13:46 UTC, IsaacJade commented on Silksong/Assets/Scripts/Dialogue/TalkSOManager.cs
> +    public DialogContainerSO DialogueContainer;
见TalkManager

2022-01-15 13:46 UTC, IsaacJade commented on Silksong/Assets/Scripts/SceneInteractive/NormaInteract.cs
>  public class NormaInteract : InteractTriggerBase<NormaInteract>
class 命名有问题

2022-01-17 01:20 UTC, Andy0evil approved these changes

2022-02-10 13:46 UTC, Iambananayeah approved these changes

2022-02-10 15:07 UTC, QAQ-FLAG approved these changes

2022-02-10 15:07 UTC, QAQ-FLAG commented on .github/CODEOWNERS
> -*       @Andy0evil @ddsurvivor @Iambananayeah @IsaacJade @QAQ-FLAG
这个文件不能被改

2022-02-14 07:46 UTC, IsaacJade approved these changes

2022-02-14 07:55 UTC, merged